# Generated by Django 4.0.6 on 2022-07-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0002_profil_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profil',
        ),
    ]
