# Generated by Django 4.0.6 on 2022-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(),
        ),
    ]
