# Generated by Django 4.0.6 on 2022-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0009_likepost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_img',
            field=models.ImageField(default='default-profile-icon-16.png', upload_to='post_profile_img'),
        ),
    ]
