# Generated by Django 4.0.6 on 2022-07-30 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0012_profile_no_of_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='no_of_followers',
            new_name='following',
        ),
    ]
