# Generated by Django 4.0.6 on 2022-07-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0013_rename_no_of_followers_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='follower_img',
            field=models.ImageField(default='', upload_to='fllwer_img'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user_img',
            field=models.ImageField(default='', upload_to='user_img'),
        ),
    ]
