# Generated by Django 4.0.6 on 2022-07-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fible_app', '0014_follow_follower_img_follow_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='tof',
            field=models.BooleanField(default=False),
        ),
    ]
